version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 25
    versioning-strategy: "auto"


