version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Sao_Paulo"
      target-branch: "master"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "@types/node"
    versioning-strategy: "auto"


